/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hamster.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
hamster_rpc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		hmstr_collect_in hmstr_collect_rpc_1_arg;
		hmstr_directory_in hmst_directory_rpc_1_arg;
		hmstr_givetreats_in hmstr_givetreats_rpc_1_arg;
		hmstr_howsdoing_in hmstr_howsdoing_rpc_1_arg;
		hmstr_lookup_in hmstr_lookup_rpc_1_arg;
		hmstr_readentry_in hmstr_readentry_rpc_1_arg;
		hmstr_new_in hmstr_new_rpc_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case HMSTR_COLLECT_RPC:
		_xdr_argument = (xdrproc_t) xdr_hmstr_collect_in;
		_xdr_result = (xdrproc_t) xdr_hmstr_collect_out;
		local = (char *(*)(char *, struct svc_req *)) hmstr_collect_rpc_1_svc;
		break;

	case HMST_DIRECTORY_RPC:
		_xdr_argument = (xdrproc_t) xdr_hmstr_directory_in;
		_xdr_result = (xdrproc_t) xdr_hmstr_directory_out;
		local = (char *(*)(char *, struct svc_req *)) hmst_directory_rpc_1_svc;
		break;

	case HMSTR_GIVETREATS_RPC:
		_xdr_argument = (xdrproc_t) xdr_hmstr_givetreats_in;
		_xdr_result = (xdrproc_t) xdr_hmstr_givetreats_out;
		local = (char *(*)(char *, struct svc_req *)) hmstr_givetreats_rpc_1_svc;
		break;

	case HMSTR_HOWSDOING_RPC:
		_xdr_argument = (xdrproc_t) xdr_hmstr_howsdoing_in;
		_xdr_result = (xdrproc_t) xdr_hmstr_howsdoing_out;
		local = (char *(*)(char *, struct svc_req *)) hmstr_howsdoing_rpc_1_svc;
		break;

	case HMSTR_LOOKUP_RPC:
		_xdr_argument = (xdrproc_t) xdr_hmstr_lookup_in;
		_xdr_result = (xdrproc_t) xdr_hmstr_lookup_out;
		local = (char *(*)(char *, struct svc_req *)) hmstr_lookup_rpc_1_svc;
		break;

	case HMSTR_READENTRY_RPC:
		_xdr_argument = (xdrproc_t) xdr_hmstr_readentry_in;
		_xdr_result = (xdrproc_t) xdr_hmstr_readentry_out;
		local = (char *(*)(char *, struct svc_req *)) hmstr_readentry_rpc_1_svc;
		break;

	case HMSTR_NEW_RPC:
		_xdr_argument = (xdrproc_t) xdr_hmstr_new_in;
		_xdr_result = (xdrproc_t) xdr_hmstr_new_out;
		local = (char *(*)(char *, struct svc_req *)) hmstr_new_rpc_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (HAMSTER_RPC, HMSTR_COLLECT_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, HAMSTER_RPC, HMSTR_COLLECT_VERS, hamster_rpc_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (HAMSTER_RPC, HMSTR_COLLECT_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, HAMSTER_RPC, HMSTR_COLLECT_VERS, hamster_rpc_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (HAMSTER_RPC, HMSTR_COLLECT_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
