/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HAMSTER_H_RPCGEN
#define _HAMSTER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *nameString;

//shadows the hmstr_state struct implemented in hamsterlib
struct hmstrState {
	uint16_t treats_left;
	uint32_t rounds;
	int16_t cost;
};
typedef struct hmstrState hmstrState;

//in/out params for new
struct hmstr_new_in {
	nameString owner;
	nameString hamster;
	uint16_t treats;
};
typedef struct hmstr_new_in hmstr_new_in;

struct hmstr_new_out {
	int32_t id;
};
typedef struct hmstr_new_out hmstr_new_out;

struct hmstr_lookup_in {
	nameString owner;
	nameString hamster;
};
typedef struct hmstr_lookup_in hmstr_lookup_in;

struct hmstr_lookup_out {
	int32_t id;
};
typedef struct hmstr_lookup_out hmstr_lookup_out;

struct hmstr_directory_in {
	int32_t fdptr;
	nameString owner;
	nameString hamster;
};
typedef struct hmstr_directory_in hmstr_directory_in;

struct hmstr_directory_out {
	int32_t id;
	int32_t fdptr;
};
typedef struct hmstr_directory_out hmstr_directory_out;

struct hmstr_howsdoing_in {
	int32_t id;
};
typedef struct hmstr_howsdoing_in hmstr_howsdoing_in;

struct hmstr_howsdoing_out {
	int32_t retVal;
	hmstrState state;
};
typedef struct hmstr_howsdoing_out hmstr_howsdoing_out;

struct hmstr_readentry_in {
	int32_t id;
};
typedef struct hmstr_readentry_in hmstr_readentry_in;

struct hmstr_readentry_out {
	int32_t treats;
	nameString owner;
	nameString name;
	int16_t price;
};
typedef struct hmstr_readentry_out hmstr_readentry_out;

struct hmstr_givetreats_in {
	int32_t id;
	uint16_t treats;
};
typedef struct hmstr_givetreats_in hmstr_givetreats_in;

struct hmstr_givetreats_out {
	int32_t treats;
};
typedef struct hmstr_givetreats_out hmstr_givetreats_out;

struct hmstr_collect_in {
	nameString owner;
};
typedef struct hmstr_collect_in hmstr_collect_in;

struct hmstr_collect_out {
	int32_t price;
};
typedef struct hmstr_collect_out hmstr_collect_out;

#define HAMSTER_RPC 0x1BADBABE
#define HMSTR_COLLECT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HMSTR_COLLECT_RPC 1
extern  hmstr_collect_out * hmstr_collect_rpc_1(hmstr_collect_in *, CLIENT *);
extern  hmstr_collect_out * hmstr_collect_rpc_1_svc(hmstr_collect_in *, struct svc_req *);
#define HMST_DIRECTORY_RPC 2
extern  hmstr_directory_out * hmst_directory_rpc_1(hmstr_directory_in *, CLIENT *);
extern  hmstr_directory_out * hmst_directory_rpc_1_svc(hmstr_directory_in *, struct svc_req *);
#define HMSTR_GIVETREATS_RPC 3
extern  hmstr_givetreats_out * hmstr_givetreats_rpc_1(hmstr_givetreats_in *, CLIENT *);
extern  hmstr_givetreats_out * hmstr_givetreats_rpc_1_svc(hmstr_givetreats_in *, struct svc_req *);
#define HMSTR_HOWSDOING_RPC 4
extern  hmstr_howsdoing_out * hmstr_howsdoing_rpc_1(hmstr_howsdoing_in *, CLIENT *);
extern  hmstr_howsdoing_out * hmstr_howsdoing_rpc_1_svc(hmstr_howsdoing_in *, struct svc_req *);
#define HMSTR_LOOKUP_RPC 5
extern  hmstr_lookup_out * hmstr_lookup_rpc_1(hmstr_lookup_in *, CLIENT *);
extern  hmstr_lookup_out * hmstr_lookup_rpc_1_svc(hmstr_lookup_in *, struct svc_req *);
#define HMSTR_READENTRY_RPC 6
extern  hmstr_readentry_out * hmstr_readentry_rpc_1(hmstr_readentry_in *, CLIENT *);
extern  hmstr_readentry_out * hmstr_readentry_rpc_1_svc(hmstr_readentry_in *, struct svc_req *);
#define HMSTR_NEW_RPC 7
extern  hmstr_new_out * hmstr_new_rpc_1(hmstr_new_in *, CLIENT *);
extern  hmstr_new_out * hmstr_new_rpc_1_svc(hmstr_new_in *, struct svc_req *);
extern int hamster_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HMSTR_COLLECT_RPC 1
extern  hmstr_collect_out * hmstr_collect_rpc_1();
extern  hmstr_collect_out * hmstr_collect_rpc_1_svc();
#define HMST_DIRECTORY_RPC 2
extern  hmstr_directory_out * hmst_directory_rpc_1();
extern  hmstr_directory_out * hmst_directory_rpc_1_svc();
#define HMSTR_GIVETREATS_RPC 3
extern  hmstr_givetreats_out * hmstr_givetreats_rpc_1();
extern  hmstr_givetreats_out * hmstr_givetreats_rpc_1_svc();
#define HMSTR_HOWSDOING_RPC 4
extern  hmstr_howsdoing_out * hmstr_howsdoing_rpc_1();
extern  hmstr_howsdoing_out * hmstr_howsdoing_rpc_1_svc();
#define HMSTR_LOOKUP_RPC 5
extern  hmstr_lookup_out * hmstr_lookup_rpc_1();
extern  hmstr_lookup_out * hmstr_lookup_rpc_1_svc();
#define HMSTR_READENTRY_RPC 6
extern  hmstr_readentry_out * hmstr_readentry_rpc_1();
extern  hmstr_readentry_out * hmstr_readentry_rpc_1_svc();
#define HMSTR_NEW_RPC 7
extern  hmstr_new_out * hmstr_new_rpc_1();
extern  hmstr_new_out * hmstr_new_rpc_1_svc();
extern int hamster_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nameString (XDR *, nameString*);
extern  bool_t xdr_hmstrState (XDR *, hmstrState*);
extern  bool_t xdr_hmstr_new_in (XDR *, hmstr_new_in*);
extern  bool_t xdr_hmstr_new_out (XDR *, hmstr_new_out*);
extern  bool_t xdr_hmstr_lookup_in (XDR *, hmstr_lookup_in*);
extern  bool_t xdr_hmstr_lookup_out (XDR *, hmstr_lookup_out*);
extern  bool_t xdr_hmstr_directory_in (XDR *, hmstr_directory_in*);
extern  bool_t xdr_hmstr_directory_out (XDR *, hmstr_directory_out*);
extern  bool_t xdr_hmstr_howsdoing_in (XDR *, hmstr_howsdoing_in*);
extern  bool_t xdr_hmstr_howsdoing_out (XDR *, hmstr_howsdoing_out*);
extern  bool_t xdr_hmstr_readentry_in (XDR *, hmstr_readentry_in*);
extern  bool_t xdr_hmstr_readentry_out (XDR *, hmstr_readentry_out*);
extern  bool_t xdr_hmstr_givetreats_in (XDR *, hmstr_givetreats_in*);
extern  bool_t xdr_hmstr_givetreats_out (XDR *, hmstr_givetreats_out*);
extern  bool_t xdr_hmstr_collect_in (XDR *, hmstr_collect_in*);
extern  bool_t xdr_hmstr_collect_out (XDR *, hmstr_collect_out*);

#else /* K&R C */
extern bool_t xdr_nameString ();
extern bool_t xdr_hmstrState ();
extern bool_t xdr_hmstr_new_in ();
extern bool_t xdr_hmstr_new_out ();
extern bool_t xdr_hmstr_lookup_in ();
extern bool_t xdr_hmstr_lookup_out ();
extern bool_t xdr_hmstr_directory_in ();
extern bool_t xdr_hmstr_directory_out ();
extern bool_t xdr_hmstr_howsdoing_in ();
extern bool_t xdr_hmstr_howsdoing_out ();
extern bool_t xdr_hmstr_readentry_in ();
extern bool_t xdr_hmstr_readentry_out ();
extern bool_t xdr_hmstr_givetreats_in ();
extern bool_t xdr_hmstr_givetreats_out ();
extern bool_t xdr_hmstr_collect_in ();
extern bool_t xdr_hmstr_collect_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HAMSTER_H_RPCGEN */
